// export const LOAD_HOME_PAGE = 'LOAD_HOME_PAGE'
// export const LOAD_SEARCH_PAGE = 'LOAD_SEARCH_PAGE'
// export const LOAD_DISPLAY_CAR_PAGE = 'LOAD_DISPLAY_CAR_PAGE'

export const FETCH_CAR_OF_THE_WEEK_STARTED = 'FETCH_CAR_OF_THE_WEEK_STARTED'
export const FETCH_CAR_OF_THE_WEEK_LOADED = 'FETCH_CAR_OF_THE_WEEK_LOADED'
export const FETCH_CAR_OF_THE_WEEK_ERROR = 'FETCH_CAR_OF_THE_WEEK_ERROR'

export const FETCH_MAKES_STARTED = 'FETCH_MAKES_STARTED'
export const FETCH_MAKES_LOADED = 'FETCH_MAKES_LOADED'
export const FETCH_MAKES_ERROR = 'FETCH_MAKES_ERROR'

export const FETCH_MODELS_STARTED = 'FETCH_MODELS_STARTED'
export const FETCH_MODELS_LOADED = 'FETCH_MODELS_LOADED'
export const FETCH_MODELS_ERROR = 'FETCH_MODELS_ERROR'

export const SEARCH_STARTED = 'SEARCH_STARTED'
export const SELECT_MAKE = 'SELECT_MAKE'
export const SELECT_MODEL = 'SELECT_MODEL'
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH'

export const NAVIGATE = 'NAVIGATE'
